### ISSUE TITLE
Project Feedback

### ISSUE THREAD

**Issue by thedarkjester** [JustinChan1996/blockchain-developer-bootcamp-final-project#1]
Some initial feedback on your project:

1. The level of testing is something I personally recommend and appreciate, however, a clean compile has a lot failing - this needs correcting for me to continue
2. There was a compilation error `dateCreated` should be the value in your `@param` line on line 102
3. Consider changing the modifiers that state them as storage types as memory, should save some gas as it won't allocate it to storage while processing

**Comment by JustinChan1996** [comment]
Already fixed the @param line on line 102 and fixed the dates in the test cases so all the tests can run successfully. Thanks for the feedback.
